# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

im_equ <- function(A, b) {
    .Call('_polysf_im_equ', PACKAGE = 'polysf', A, b)
}

lasso_fr <- function(Omega, pi) {
    .Call('_polysf_lasso_fr', PACKAGE = 'polysf', Omega, pi)
}

#' @name ind_rows
#' @title Select independent rows of a matrix
#' @description Given any matrix \code{M}, this function selects the first \code{r=rank(M)} 
#' independent rows in \code{M} which form a row basis of \code{M}. 
#' @param M A matrix.
#' @return The function \code{ind_rows} returns a list containing the following components:
#'   \item{N}{A matrix with \code{r=rank(M)} rows. Its rows come from the selected independent rows in \code{M}.}
#'   \item{idx}{A logical vector. An element is \code{TRUE} if the corresponding row in \code{M} is selected, \code{FALSE} otherwise.}
#' @examples
#' # generate a matrix M of rank 2 with dependent rows
#' M = matrix(rnorm(16), nrow = 4)
#' M[2,] = rnorm(1) * M[1,] + rnorm(1) * M[3,]
#' M[4,] = rnorm(1) * M[2,] + rnorm(1) * M[3,]
#' 
#' # select the first 2 independent rows
#' ind_rows(M)
ind_rows <- function(M) {
    .Call('_polysf_ind_rows', PACKAGE = 'polysf', M)
}

#' @name add_to_full
#' @title Extend a full-row-rank matrix to a full-rank square matrix.
#' @description Given any full-row-rank matrix \code{N} with \code{n=ncol(N)} and \code{r=rank(N)}. 
#' This function adds \code{n-r} independent rows to the matrix \code{N}, 
#' such that the resulting new matrix is a full-rank square matrix.  
#' @param N A full-row-rank matrix.
#' @return A full-rank square matrix whose first \code{r} rows come from \code{N}.
#' @examples 
#' # generate a full-row-rank matrix
#' N = matrix(rnorm(10), nrow = 2)
#' 
#' # add 3 independent rows to the matrix to form a full-rank square matrix
#' add_to_full(N)
add_to_full <- function(N) {
    .Call('_polysf_add_to_full', PACKAGE = 'polysf', N)
}

